/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_glview_blur_Blur */

#ifndef _Included_com_glview_blur_Blur
#define _Included_com_glview_blur_Blur
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_glview_blur_Blur
 * Method:    blur
 * Signature: ([BIIIIIII)V
 */
JNIEXPORT void JNICALL Java_com_glview_blur_Blur_blur
  (JNIEnv *, jclass, jbyteArray, jint, jint, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
