/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_glview_font_FontUtils */

#ifndef _Included_com_glview_font_FontUtils
#define _Included_com_glview_font_FontUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_glview_font_FontUtils
 * Method:    loadGlyphBitmap
 * Signature: (Ljava/nio/ByteBuffer;IIIILjava/nio/ByteBuffer;IIII)V
 */
JNIEXPORT void JNICALL Java_com_glview_font_FontUtils_loadGlyphBitmap__Ljava_nio_ByteBuffer_2IIIILjava_nio_ByteBuffer_2IIII
  (JNIEnv *, jclass, jobject, jint, jint, jint, jint, jobject, jint, jint, jint, jint);

/*
 * Class:     com_glview_font_FontUtils
 * Method:    loadGlyphBitmap
 * Signature: ([BIIIILjava/nio/ByteBuffer;IIII)V
 */
JNIEXPORT void JNICALL Java_com_glview_font_FontUtils_loadGlyphBitmap___3BIIIILjava_nio_ByteBuffer_2IIII
  (JNIEnv *, jclass, jbyteArray, jint, jint, jint, jint, jobject, jint, jint, jint, jint);

/*
 * Class:     com_glview_font_FontUtils
 * Method:    loadGlyphBlurBitmap
 * Signature: (Ljava/nio/ByteBuffer;IIILjava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_com_glview_font_FontUtils_loadGlyphBlurBitmap__Ljava_nio_ByteBuffer_2IIILjava_nio_ByteBuffer_2I
  (JNIEnv *, jclass, jobject, jint, jint, jint, jobject, jint);

/*
 * Class:     com_glview_font_FontUtils
 * Method:    loadGlyphBlurBitmap
 * Signature: (Ljava/nio/ByteBuffer;III[BI)V
 */
JNIEXPORT void JNICALL Java_com_glview_font_FontUtils_loadGlyphBlurBitmap__Ljava_nio_ByteBuffer_2III_3BI
  (JNIEnv *, jclass, jobject, jint, jint, jint, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
