/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_glview_utils_BufferUtils */

#ifndef _Included_com_glview_utils_BufferUtils
#define _Included_com_glview_utils_BufferUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_glview_utils_BufferUtils
 * Method:    copyJni
 * Signature: (Ljava/nio/Buffer;ILjava/nio/Buffer;II)V
 */
JNIEXPORT void JNICALL Java_com_glview_utils_BufferUtils_copyJni
  (JNIEnv *, jclass, jobject, jint, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
